language: node_js

os:
- linux

node_js:
- "stable"

script:
- |
  echo ">>> Compile vscode-test"
  yarn && yarn compile
  echo ">>> Compiled vscode-test"
  cd sample
  echo ">>> Run sample integration test"
  yarn && yarn compile && yarn test

cache: yarn
